server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - "localhost"
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: syslog
  static_configs:
  - targets:
      - "localhost"
    labels:
      job: syslog
      __path__: /var/log/remote/syslog.log
  pipeline_stages:
  - regex:
      expression: '^<(?P<priority>\d+)>(?P<timestamp>\S+) (?P<hostname>\S+) (?P<tag>\S+): (?P<message>.*)$'
  - labels:
      hostname:
      tag:
  - timestamp:
      source: timestamp
      format: RFC3339